import type { CharacterProfileData } from './types'

export const MOCK_CHARACTER: CharacterProfileData = {
  name: 'Jinhsi',
  element: 'spectro',
  level: 90,
  sequenceLevel: 2,
  stats: [
    { name: 'HP', value: 15230, displayValue: '15,230' },
    { name: 'ATK', value: 2847, displayValue: '2,847' },
    { name: 'DEF', value: 1102, displayValue: '1,102' },
    { name: 'Crit Rate', value: 62.4, displayValue: '62.4%' },
    { name: 'Crit DMG', value: 218.6, displayValue: '218.6%' },
    { name: 'Energy Regen', value: 142.5, displayValue: '142.5%' },
    { name: 'Resonance Skill', value: 45.2, displayValue: '45.2%' },
    { name: 'Basic Attack', value: 38.0, displayValue: '38.0%' },
    { name: 'Heavy Attack', value: 22.5, displayValue: '22.5%' },
    { name: 'Liberation', value: 55.8, displayValue: '55.8%' },
  ],
  sequences: [
    { name: "Loong's Halo", description: "Incarnation: When Jinhsi's Intro Skill is cast, all team members' Spectro DMG Bonus is increased by 20% for 28s." },
    { name: 'Phénix Plume', description: "Incarnation: Resonance Skill DMG Bonus is increased by 20%. When Incarnation's Resonance Skill hits a target, Jinhsi restores 5 Resonance Energy." },
    { name: 'Radiant Surge', description: 'Incarnation: Resonance Liberation DMG Multiplier is increased by 58%.' },
    { name: 'Flowing Illumination', description: 'When casting Intro Skill, Jinhsi gains 2 stacks of Ordination Glow, each increasing her ATK by 20% for 28s, up to 2 stacks.' },
    { name: 'Divine Maiden', description: "When Incarnation's Heavy Attack: Incarnation hits a target, the damage dealt by Jinhsi's Outro Skill to the target increases by 50% for 28s." },
    { name: 'Homecoming', description: "Incarnation: Resonance Liberation's Crit DMG is increased by 45%." },
  ],
  setBonuses: [
    { setName: 'Celestial Light', pieces: 2, description: 'Spectro DMG Bonus +10%.' },
    { setName: 'Celestial Light', pieces: 5, description: 'Spectro DMG Bonus +30% for 15s after releasing Intro Skill.' },
  ],
  echoes: [
    {
      id: 'e1',
      name: 'Jué',
      cost: 4,
      level: 25,
      rarity: 5,
      mainStat: { name: 'Spectro DMG', value: '30%' },
      subStats: [
        { name: 'ATK%', value: '9.4%' },
        { name: 'Crit Rate', value: '8.7%' },
        { name: 'Crit DMG', value: '15.6%' },
        { name: 'Energy Regen', value: '7.2%' },
        { name: 'ATK', value: '40' },
      ],
      setName: 'Celestial Light',
    },
    {
      id: 'e2',
      name: 'Hoochief',
      cost: 3,
      level: 25,
      rarity: 5,
      mainStat: { name: 'Spectro DMG', value: '30%' },
      subStats: [
        { name: 'ATK%', value: '8.1%' },
        { name: 'Crit DMG', value: '17.2%' },
        { name: 'DEF%', value: '6.4%' },
        { name: 'HP%', value: '5.3%' },
        { name: 'ATK', value: '30' },
      ],
      setName: 'Celestial Light',
    },
    {
      id: 'e3',
      name: 'Fusion Dreadmane',
      cost: 1,
      level: 25,
      rarity: 5,
      mainStat: { name: 'ATK%', value: '18%' },
      subStats: [
        { name: 'Crit Rate', value: '7.5%' },
        { name: 'ATK', value: '35' },
        { name: 'HP', value: '430' },
        { name: 'DEF%', value: '5.8%' },
        { name: 'Crit DMG', value: '9.2%' },
      ],
      setName: 'Celestial Light',
    },
    {
      id: 'e4',
      name: 'Glacio Predator',
      cost: 1,
      level: 25,
      rarity: 5,
      mainStat: { name: 'ATK%', value: '18%' },
      subStats: [
        { name: 'Crit DMG', value: '13.8%' },
        { name: 'Crit Rate', value: '6.9%' },
        { name: 'ATK%', value: '6.1%' },
        { name: 'HP', value: '390' },
        { name: 'DEF', value: '40' },
      ],
      setName: 'Celestial Light',
    },
    {
      id: 'e5',
      name: 'Aero Predator',
      cost: 1,
      level: 25,
      rarity: 5,
      mainStat: { name: 'ATK%', value: '18%' },
      subStats: [
        { name: 'ATK%', value: '7.8%' },
        { name: 'Energy Regen', value: '6.1%' },
        { name: 'Crit Rate', value: '5.5%' },
        { name: 'Crit DMG', value: '11.4%' },
        { name: 'HP%', value: '4.9%' },
      ],
      setName: 'Celestial Light',
    },
  ],
  weapon: {
    id: 'w1',
    name: 'Ages of Harvest',
    level: 90,
    rank: 1,
    rarity: 5,
    baseAtk: 587,
    subStat: { name: 'Crit Rate', value: '22.1%' },
    passive: "Increases Resonance Skill DMG by 12%. Normal Attack or Heavy Attack that hits a target grants 1 stack of Ageless Marking, stacking up to 3 times. Each stack increases the equipper's ATK by 4.8% for 7s.",
  },
}
