// Converts between a simulated timeline and the user step list: extract steps, merge Edit-Mode inserts, delete caps.
import type { Snapshot } from '../../types/snapshot'
import type { RotationStep } from '../../types/rotation'
import type { EditModeEntry } from '../../types/editMode'

/**
 * Extracts the user-defined (character, action) pairs from a snapshot array.
 * Skips blank rows and rows marked `isAutocast` (Outro/Intro and auto-cast follow-ups),
 * since those are re-generated by the engine on import.
 */
export function extractSteps(snapshots: Snapshot[]): RotationStep[] {
  return snapshots
    .filter(s => s.action && s.action !== '' && s.character && !s.isAutocast)
    .map(s => ({ character: s.character!, action: s.action! }))
}

/**
 * Merges Edit-Mode insertions into the user step list.
 * Entries are applied in insertAfterStepCount order; each insertion shifts later positions by one
 * so that every entry lands after the Nth *original* step.
 */
export function mergeEditModeSteps(steps: RotationStep[], entries: EditModeEntry[]): RotationStep[] {
  const sorted = [...entries].sort((a, b) => a.insertAfterStepCount - b.insertAfterStepCount)
  const merged = [...steps]
  let offset = 0
  for (const entry of sorted) {
    merged.splice(entry.insertAfterStepCount + offset, 0, { character: entry.character, action: entry.action })
    offset++
  }
  return merged
}

/**
 * When deleting an autocast follow-up row, we want to replay the triggering user step
 * but regenerate only the autocasts that came BEFORE the deleted row. Walk back through
 * the consecutive autocast chain to its start, then count how many hops to allow.
 * Example: chain [user A → autocast B → autocast C], deleting C → allow 1 hop (keeps B).
 *          Deleting B → allow 0 hops (no follow-ups replayed at all).
 * Outro/Intro autocasts are NOT follow-up chains (no charactersAttemptFollowUp on the
 * row before them), so they return undefined (no cap).
 */
export function autocastHopsBeforeRow(snapshots: Snapshot[], index: number): number | undefined {
  if (!snapshots[index].isAutocast) return undefined

  const charName = snapshots[index].character ?? ''
  let chainStart = index
  while (chainStart > 0 && snapshots[chainStart - 1].isAutocast) {
    chainStart--
  }
  const triggerRow = chainStart > 0 ? snapshots[chainStart - 1] : null
  const isFollowUpChain =
    !!charName &&
    triggerRow != null &&
    !triggerRow.isAutocast &&
    !!triggerRow.action &&
    !!triggerRow.charactersAttemptFollowUp?.[charName]

  // chainStart is the index of the first autocast. index - chainStart equals the
  // number of autocast rows before the deleted one, i.e. the hops to keep.
  return isFollowUpChain ? index - chainStart : undefined
}
