import type { Snapshot } from '../types/snapshot'
import type { DamageEvent } from '../types/events'

// ========== Types ============================================================================================================

export type RotationStep = {
  character: string
  action: string
}

export type SavedRotation = {
  name: string
  createdAt: string // ISO date string
  steps: RotationStep[]
}

export type ImportError = {
  stepIndex: number
  character: string
  action: string
  reason: string
}

export type ImportRunResult = {
  snapshots: Snapshot[]
  damageEvents: DamageEvent[]
  completedSteps: number
  error: ImportError | null
}

// ========== LocalStorage =====================================================================================================

const STORAGE_KEY = 'battle-optimizer:saved-rotations'

export function loadSavedRotations(): SavedRotation[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as SavedRotation[]) : []
  } catch {
    return []
  }
}

export function saveRotationToStorage(rotation: SavedRotation): void {
  const existing = loadSavedRotations()
  const idx = existing.findIndex(r => r.name === rotation.name)
  if (idx !== -1) existing[idx] = rotation
  else existing.push(rotation)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(existing))
}

export function deleteRotationFromStorage(name: string): void {
  const existing = loadSavedRotations()
  const filtered = existing.filter(r => r.name !== name)
  localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered))
}

// ========== Step Extraction ==================================================================================================

/**
 * Extracts the user-defined (character, action) pairs from a snapshot array.
 * Skips blank rows and rows marked `isAutocast` (Outro/Intro and auto-cast follow-ups),
 * since those are re-generated by the engine on import.
 */
export function extractSteps(snapshots: Snapshot[]): RotationStep[] {
  return snapshots
    .filter(s => s.action && s.action !== '' && s.character && !s.isAutocast)
    .map(s => ({ character: s.character!, action: s.action! }))
}

// ========== File I/O =========================================================================================================

export function downloadRotationAsJson(rotation: SavedRotation): void {
  const json = JSON.stringify(rotation, null, 2)
  const blob = new Blob([json], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${rotation.name.replace(/[^a-z0-9_\-]/gi, '_')}.rotation.json`
  a.click()
  URL.revokeObjectURL(url)
}

export function parseRotationFromJson(content: string): SavedRotation | null {
  try {
    const parsed = JSON.parse(content)
    if (typeof parsed.name !== 'string' || !Array.isArray(parsed.steps)) return null
    if (!parsed.steps.every((s: unknown) => typeof (s as RotationStep).character === 'string' && typeof (s as RotationStep).action === 'string')) return null
    return parsed as SavedRotation
  } catch {
    return null
  }
}
